### ISSUE TITLE
Cannot enter numeric values

### ISSUE THREAD

**Issue by swalters** [ua9msn/datetime#2]
Great library! I've noticed this issue when trying to implement in my application

1. In docs example, click on Empty options text box
2. Get a new date
3. Click on year
4. Try to type a new year with keyboard, 2018

The value is not accepted

**Comment by Martin-Cox** [comment]
A debounce function with a suitable timeout (e.g. 300ms) wrapped around the keydown event listener would solve this.

**Comment by ua9msn** [comment]
Fixed. 
As it appears, it's required to prevent defaults. In a previous version of Chrome everything worked well, but now the default event comes after the input value changes and overwrites the calculated one.

**Comment by swalters** [comment]
@ua9msn will this release be published to NPM? thanks!
