### ISSUE TITLE
consider supporting older jquery 

### ISSUE THREAD

**Issue by swalters** [ua9msn/datetime#3]
My application uses materializecss which can't work with jquery 3.

datetime-entry seems to work fine with jquery 2.2.4

Would you consider changing your peerdependencies requirement to the lowest possible version of jquery?  I can't 'npm shrinkwrap' my application because of this dependency on jquery 3.

Or, better yet, dump jquery altogether!  It always causes dependency issues.

Thanks.

**Comment by ua9msn** [comment]
Hello @swalters 
I set jQuery version to "any".  So it should be enough to satisfy your requirements
