### ISSUE TITLE
Can drag & drop parts of the datetime and mangle the input

### ISSUE THREAD

**Issue by Martin-Cox** [ua9msn/datetime#5]
Click on the input to select part of the datetime e.g. the month. You can then click and drag that selection to a different part of the input which can lead to some really mangled inputs:
![image](https://cloud.githubusercontent.com/assets/6671098/25429958/aa9f1dcc-2a72-11e7-92ad-7d1a27bf271e.png)

Additionally, you can cut the values using the right click context menu (but this can be worked around by disabling the browser right click on the input).

Example:
https://jsfiddle.net/dhhxLjz6/2/

**Comment by ua9msn** [comment]
Please test it in the version 2. 
It is still possible to dnd or cut a value but it doesn't break functionality. Sometimes it is useful to have dnd. I do not want to disable it completely
